"""Generate remaining EoC JSON specs for all missing Assessment Scheme subjects."""
from __future__ import annotations
import json
from pathlib import Path

OUT = Path(r"f:\Mobile Apps\ZSMS\school_management_systems\data\curriculum\ecz-eoc")

def eoc(id_, desc, label, topics, unverified=None, mode="topic", note=None, tasks=None):
  sub = {
    "id": f"{id_.lower()}-main",
    "label": label,
    "topicAliases": topics or [],
    "unverifiedTopicAliases": unverified or [],
    "taskTypeAliases": tasks or [],
  }
  if note:
    sub["note"] = note
  return {
    "id": id_,
    "description": desc,
    "resolutionMode": mode,
    "subSkills": [sub],
  }

def td(code, sba_n2, sba_n3, sba_marks, fe_n, fe_marks, fe_notes, sba_bloom=("understanding","creating"), fe_bloom=("understanding","evaluating"), min_parts=2, sba_notes=None):
  return {
    "components": [
      {"type":"SBA","code":f"{code}/1","formLevel":"Form 2","numItems":sba_n2,"totalMarks":sba_marks,
       "structureNotes": sba_notes or f"SBA Form 2: {sba_n2} tasks/{sba_marks} marks.",
       "bloomRange": list(sba_bloom)},
      {"type":"SBA","code":f"{code}/1","formLevel":"Form 3","numItems":sba_n3,"totalMarks":sba_marks,
       "structureNotes": f"SBA Form 3: {sba_n3} tasks/{sba_marks} marks.",
       "bloomRange": list(sba_bloom)},
      {"type":"FINAL_EXAM","code":f"{code}/2","formLevel":"Form 4","numItems":fe_n,"totalMarks":fe_marks,
       "structureNotes": fe_notes, "bloomRange": list(fe_bloom)},
    ],
    "scenarioRequired": True,
    "minPartsPerScenarioItem": min_parts,
  }

def rules(*xs): return {"rules": list(xs)}
def ex(eoc_id, theme, parts, comps=("analytical_thinking","problem_solving")):
  return {"eocId": eoc_id, "scenarioTheme": theme, "parts": parts, "keyCompetences": list(comps)}

SPECS = [
  {
    "filename": "french-language-1120.json",
    "subjectCode": "1120", "subjectName": "French Language", "syllabusYear": 2024,
    "construct": "Demonstrates proficient use of listening, speaking, reading and writing skills in real-life situations, adapting to audience and purpose to communicate effectively and support life-long learning.",
    "elementsOfConstruct": [
      eoc("EoC1","Reads, interprets, summarises and translates continuous and non-continuous texts",
          "Reads/comprehends texts; interprets vocabulary; summarises; translates preserving meaning/tone",
          ["Reading Comprehension","Translation","Summary","Non-continuous texts"],
          ["Continuous texts","French reading"]),
      eoc("EoC2","Demonstrates mastery of written language conventions and transformations",
          "Spells accurately; applies grammar/syntax/punctuation; transforms written structures",
          ["Language Structure","Grammar","Composition","Letter Writing","Narrative writing","Descriptive writing"],
          ["Guided composition","Unguided composition","Curriculum vitae"]),
      eoc("EoC3","Understands and interprets spoken information",
          "Identifies main ideas in spoken texts; analyses purpose/tone; follows instructions; interprets spoken source→target",
          ["Listening","Oral comprehension","Directions"],
          ["Spoken French"], note="Primarily SBA; Final Exam focuses on EoC1-2."),
      eoc("EoC4","Produces ideas, thoughts and opinions through spoken language",
          "Organises ideas; speaks clearly/fluently; appropriate vocabulary/tone; accurate pronunciation/grammar",
          ["Speaking","Oral presentation","Pronunciation"],
          ["Conversation"], note="Primarily SBA; Final Exam focuses on EoC1-2."),
    ],
    "testDesign": td("1120", 5, 5, 90,
      10, 60,
      "Final Exam EoC1+2 only: Section A Reading (2 items); Section B Structure+Translation; Section C Writing. SBA also includes Form2-3 project (20 marks). Weighting SBA:FE 40:60. Duration 2h.",
      sba_bloom=("remembering","creating"), fe_bloom=("remembering","creating"),
      sba_notes="SBA Form 2: 5 tasks/90. All 4 EoC. Classwork, homework, oral presentations, projects. Plus shared project 20 marks across Form 2-3."),
    "scoringCriteria": rules(
      "SBA marked at school (40% with project); Final Exam centrally marked (60%).",
      "Reading passages 250-300 words; semi-structured tasks typically 15 marks each.",
      "Composition: guided and unguided (10 marks each part).",
      "Both components required for grading."),
    "exemplars": [ex("EoC1","French continuous/non-continuous reading scenarios with semi-structured comprehension tasks",
      [{"label":"(a)","marks":5,"bloomLevel":"understanding"},{"label":"(b)","marks":5,"bloomLevel":"applying"},{"label":"(c)","marks":5,"bloomLevel":"analysing"}],
      ("communication","analytical_thinking"))],
  },
  {
    "filename": "chinese-language-1125.json",
    "subjectCode": "1125", "subjectName": "Chinese Language", "syllabusYear": 2024,
    "construct": "Demonstrates proficient use of listening, speaking, reading and writing skills in real-life situations, adapting to audience and purpose to communicate effectively and support life-long learning.",
    "elementsOfConstruct": [
      eoc("EoC1","Reads, interprets, summarises and translates continuous and non-continuous texts",
          "Reads/comprehends Chinese texts; interprets vocabulary; summarises; translates preserving meaning",
          ["Reading Comprehension","Translation","Summary"], ["Chinese characters","Pinyin"]),
      eoc("EoC2","Demonstrates mastery of written language conventions and transformations",
          "Applies orthography, grammar, punctuation and written transformations accurately",
          ["Language Structure","Composition","Writing"], ["Characters","Stroke order"]),
      eoc("EoC3","Understands and interprets spoken information",
          "Identifies main ideas in spoken Chinese; analyses tone/intent; responds appropriately",
          ["Listening","Oral comprehension"], ["HSK listening"], note="Primarily SBA-focused oral/listening."),
      eoc("EoC4","Produces ideas, thoughts and opinions through spoken language",
          "Organises ideas; speaks clearly; appropriate vocabulary/tone for audience",
          ["Speaking","Oral presentation"], ["Conversation"], note="Primarily SBA-focused speaking."),
    ],
    "testDesign": td("1125", 5, 5, 90, 10, 60,
      "Parallel language scheme to French: SBA all 4 EoC; Final Exam reading/writing-focused. Codes 1125/1 and 1125/2.",
      sba_bloom=("remembering","creating"), fe_bloom=("remembering","creating")),
    "scoringCriteria": rules("SBA school-marked; Final Exam ECZ-marked.","Both components required for grading."),
    "exemplars": [ex("EoC1","Chinese reading/translation scenario for continuous and non-continuous texts",
      [{"label":"(a)","marks":5,"bloomLevel":"understanding"},{"label":"(b)","marks":5,"bloomLevel":"applying"}],
      ("communication","analytical_thinking"))],
  },
  {
    "filename": "zambian-languages-1211.json",
    "subjectCode": "1211", "subjectName": "Zambian Languages", "syllabusYear": 2024,
    "construct": "Demonstrates proficient use of listening, speaking, reading and writing skills in real-life situations, adapting to audience and purpose to communicate effectively and support life long learning.",
    "elementsOfConstruct": [
      eoc("EoC1","Demonstrates masterly of written language conventions",
          "Uses words with orthographic accuracy; applies grammar/punctuation; figurative language; writes continuous/non-continuous texts",
          ["Writing","Grammar","Orthography","Figurative language","Composition"], ["Essay writing"]),
      eoc("EoC2","Interprets, summarises and translates continuous and non-continuous texts",
          "Reads and understands texts; accurate word use for audience; translates; summarises in writing",
          ["Reading","Comprehension","Summary","Translation"], ["Non-continuous texts"]),
      eoc("EoC3","Interprets and understands spoken information",
          "Identifies main ideas; analyses purpose/tone; follows instructions; interprets spoken source→target",
          ["Listening","Oral comprehension"], ["Spoken interpretation"], note="SBA-heavy oral/listening."),
      eoc("EoC4","Expresses ideas, thoughts and opinions through spoken language",
          "Presents ideas logically; speaks clearly; appropriate vocabulary/tone for purpose and audience",
          ["Speaking","Oral presentation"], ["Discussion"], note="SBA-heavy speaking."),
    ],
    "testDesign": td("1211", 6, 6, 100, 4, 100,
      "Shared scheme across language codes 1211–1217 (Lunda, Luvale, Kiikaonde, Silozi, Chitonga, Icibemba, Cinyanja). SBA 30% / FE 70%. Use subjectCode for the specific language paper when generating.",
      sba_bloom=("remembering","creating"), fe_bloom=("understanding","creating")),
    "scoringCriteria": rules(
      "One assessment scheme covers codes 1211–1217; load by language code when available.",
      "SBA 30%, Final Exam 70%.","Both components required."),
    "exemplars": [ex("EoC2","Reading, summary and translation scenario in a Zambian language community context",
      [{"label":"(a)","marks":10,"bloomLevel":"understanding"},{"label":"(b)","marks":10,"bloomLevel":"applying"}],
      ("communication","critical_thinking"))],
  },
  {
    "filename": "musical-arts-5014.json",
    "subjectCode": "5014", "subjectName": "Musical Arts", "syllabusYear": 2024,
    "construct": "Demonstrates musical proficiency through analysing, composing and performing across diverse contexts.",
    "elementsOfConstruct": [
      eoc("EoC1","Analyses pitch","Analyses pitch in melodies and harmony",["Pitch","Melody","Harmony"],["Intervals"]),
      eoc("EoC2","Creates Melodies","Creates and analyzes melodies using the elements of music",["Melody writing","Composition","Elements of music"],["Sight reading"]),
      eoc("EoC3","Arranges Musical Scores","Arranges music scores for musical instruments",["Arrangement","Musical scores","Instrumentation"],["Orchestration"]),
      eoc("EoC4","Applies Musical Knowledge and Skills to Generate Income","Earns a living through musical skills",["Entrepreneurship","Music business"],["Performance career"]),
      eoc("EoC5","Analyses World Music","Characteristics of world music and how to use technology to produce it",["World music","Zambian musical styles","Traditional music"],["Music technology","Kalindula","Zamrock"]),
    ],
    "testDesign": td("5014", 3, 4, 100, 5, 100,
      "SBA: listening, performing, composing project (Form 2-3). Final: composing/arranging/analysing, ~1h30. Weighting 30:70.",
      sba_bloom=("understanding","creating"), fe_bloom=("understanding","creating")),
    "scoringCriteria": rules("SBA school-marked listening/performance/composition.","Final Exam ECZ-marked.","Both components required."),
    "exemplars": [ex("EoC5","Zambian musical styles and foreign influences; roles of music in traditional ceremony",
      [{"label":"(a)","marks":5,"bloomLevel":"understanding"},{"label":"(b)","marks":5,"bloomLevel":"applying"}],
      ("creativity_and_innovation","analytical_thinking"))],
  },
  {
    "filename": "design-and-technology-8015.json",
    "subjectCode": "8015", "subjectName": "Design and Technology", "syllabusYear": 2024,
    "construct": "Applies engineering principles and uses a wide range of tools and techniques to design and make a product that addresses a real-life problem.",
    "elementsOfConstruct": [
      eoc("EoC1","Utilises various materials and techniques to produce items while adhering to safety procedures",
          "Utilises materials, processes and safety measures to make products for real-life problems",
          ["Materials","Workshop safety","Production processes"],["Tools"]),
      eoc("EoC2","Generates and develops graphical representations and models",
          "Interprets/generates ideas in drawing/sketch/graphic form; creativity in Design Process",
          ["Technical drawing","Graphics","Design Process","Modelling"],["CAD"]),
      eoc("EoC3","Designs and constructs innovative systems",
          "Analyses, designs and constructs innovative systems anchored on System Technology",
          ["Systems Technology","Structures","Mechanisms"],["Electronics systems"]),
      eoc("EoC4","Develops and implements a business idea",
          "Entrepreneurship education and cross-cutting issues in design/make projects",
          ["Entrepreneurship","Business idea"],["Market research"]),
    ],
    "testDesign": {
      "components": [
        {"type":"SBA","code":"8015/1","formLevel":"Form 2","numItems":10,"totalMarks":45,
         "structureNotes":"SBA Form 2 tests 10/45 + shared portfolio/artefact project across Form 2-3 (110 marks).",
         "bloomRange":["remembering","creating"]},
        {"type":"SBA","code":"8015/1","formLevel":"Form 3","numItems":13,"totalMarks":45,
         "structureNotes":"SBA Form 3 tests 13/45 + project. Portfolio A3 + artefact realisation.",
         "bloomRange":["remembering","creating"]},
        {"type":"FINAL_EXAM","code":"8015/2","formLevel":"Form 4","numItems":6,"totalMarks":100,
         "structureNotes":"Final Exam 6 items/100. Duration 2h45. Candidates must attempt SBA+FE.",
         "bloomRange":["understanding","creating"]},
      ],
      "scenarioRequired": True,
      "minPartsPerScenarioItem": 2,
    },
    "scoringCriteria": rules("SBA: portfolio + artefact project guided by ECZ theme.","Final Exam ECZ-marked.","Both components required for certification."),
    "exemplars": [ex("EoC2","Real-life design brief requiring sketches/graphics and design-process creativity",
      [{"label":"(a)","marks":8,"bloomLevel":"applying"},{"label":"(b)","marks":12,"bloomLevel":"creating"}],
      ("creativity_and_innovation","problem_solving"))],
  },
  {
    "filename": "fashion-and-fabrics-6012.json",
    "subjectCode": "6012", "subjectName": "Fashion and Fabrics", "syllabusYear": 2024,
    "construct": "Demonstrates understanding of fabrics, designs and constructs garments to suit market trends.",
    "elementsOfConstruct": [
      eoc("EoC1","Makes informed choices and expresses innovative skills in the fashion industry",
          "Explores fashion/fabrics careers; practices work ethics; makes informed choices",
          ["Fashion industry","Textiles and clothing","Career paths"],["Work ethics"]),
      eoc("EoC2","Demonstrates technical knowledge and skills while promoting workplace safety",
          "Drafts pattern pieces; designs styles; sustainable needlework tools and garment construction",
          ["Pattern drafting","Garment construction","Needlework"],["Workplace safety"]),
      eoc("EoC3","Develops habits and sense of responsibility in managing personal and social development",
          "Personal hygiene/health habits; grooming and cosmetology techniques",
          ["Personal hygiene","Grooming","Cosmetology"],["Health habits"]),
      eoc("EoC4","Demonstrates knowledge on the use, care and improvisation of tools and material in fashion industry for economic use of tools and materials",
          "Designs articles from local materials; utilises tools for crafts",
          ["Crafts","Tools and materials","Improvisation"],["Needlework crafts"]),
      eoc("EoC5","Expresses awareness of create income generating opportunities for self-reliance and economic growth",
          "Entrepreneurial skills; manages textile enterprise; consumer rights and wise shopping",
          ["Entrepreneurship","Textile enterprise","Consumer rights"],["Marketing"]),
    ],
    "testDesign": td("6012", 5, 5, 100, 5, 100,
      "SBA Form 2-3 (30%); Final Exam Form 4 (70%). Codes 6012/1 and 6012/2.",
      sba_bloom=("remembering","creating"), fe_bloom=("understanding","creating")),
    "scoringCriteria": rules("SBA school-marked.","Final Exam ECZ-marked.","Both components required."),
    "exemplars": [ex("EoC2","Pattern drafting / garment construction scenario with workplace safety",
      [{"label":"(a)","marks":8,"bloomLevel":"applying"},{"label":"(b)","marks":12,"bloomLevel":"creating"}],
      ("creativity_and_innovation","problem_solving"))],
  },
  {
    "filename": "food-and-nutrition-6014.json",
    "subjectCode": "6014", "subjectName": "Food and Nutrition", "syllabusYear": 2024,
    "construct": "Applies food and nutrition knowledge and practical skills for healthy living, food security and entrepreneurship.",
    "elementsOfConstruct": [
      eoc("EoC1","Explores the Kitchen, equipment, utensils and materials",
          "Uses kitchen equipment/utensils/materials safely and effectively",
          ["Kitchen equipment","Utensils","Kitchen safety"],["Materials"]),
      eoc("EoC2","Understands Fundamentals of Food and Nutrition",
          "Applies fundamentals of food and nutrition science",
          ["Nutrition","Nutrients","Balanced diet"],["Food science"]),
      eoc("EoC3","Prepares and Serves Meals and Dishes",
          "Prepares and serves meals/dishes to appropriate standards",
          ["Meal preparation","Food service","Cookery"],["Menu planning"]),
      eoc("EoC4","Innovates Food Packaging and Storage Solutions",
          "Innovates packaging and storage solutions for food products",
          ["Food packaging","Food storage","Preservation"],["Labelling"]),
      eoc("EoC5","Demonstrates Knowledge and Practices that Promote Sustainable Food Security",
          "Promotes sustainable food security practices",
          ["Food security","Sustainability"],["Food waste"]),
      eoc("EoC6","Develops Skills in Consumers and Entrepreneurs through Research",
          "Consumer and entrepreneurship skills through research",
          ["Consumer education","Entrepreneurship","Research"],["Food business"]),
    ],
    "testDesign": td("6014", 5, 5, 100, 6, 100,
      "SBA Form 2-3; Final Exam Form 4. Codes 6014/1 and 6014/2. All 6 EoC.",
      sba_bloom=("remembering","creating"), fe_bloom=("understanding","creating")),
    "scoringCriteria": rules("SBA school-marked practical/theory tasks.","Final Exam ECZ-marked.","Both components required."),
    "exemplars": [ex("EoC3","Meal preparation and service scenario for a Zambian community event",
      [{"label":"(a)","marks":8,"bloomLevel":"applying"},{"label":"(b)","marks":12,"bloomLevel":"creating"}],
      ("problem_solving","creativity_and_innovation"))],
  },
  {
    "filename": "hospitality-management-6015.json",
    "subjectCode": "6015", "subjectName": "Hospitality Management", "syllabusYear": 2024,
    "construct": "Applies hospitality knowledge and skills to deliver quality guest experiences and entrepreneurial solutions.",
    "elementsOfConstruct": [
      eoc("EoC1","Understands the history of hospitality",
          "Demonstrates understanding of hospitality history and industry context",
          ["History of hospitality","Hospitality industry"],["Tourism links"]),
      eoc("EoC2","Delivers quality guest experience and coordinates effectively with other departments in",
          "Delivers quality guest experience; coordinates across hospitality departments",
          ["Guest relations","Front office","Housekeeping"],["Customer service"]),
      eoc("EoC3","Demonstrates skills in food technology and preparation",
          "Food technology and preparation skills for hospitality settings",
          ["Food preparation","Food technology","Catering"],["Kitchen operations"]),
      eoc("EoC4","Applies entrepreneurial skills in hospitality business",
          "Entrepreneurial skills for hospitality business ventures",
          ["Entrepreneurship","Hospitality business"],["Event management"]),
    ],
    "testDesign": td("6015", 5, 5, 100, 5, 100,
      "SBA Form 2-3; Final Exam Form 4. Codes 6015/1 and 6015/2.",
      sba_bloom=("remembering","creating"), fe_bloom=("understanding","creating")),
    "scoringCriteria": rules("SBA school-marked.","Final Exam ECZ-marked.","Both components required."),
    "exemplars": [ex("EoC2","Hotel guest-experience coordination scenario across departments",
      [{"label":"(a)","marks":8,"bloomLevel":"applying"},{"label":"(b)","marks":12,"bloomLevel":"evaluating"}],
      ("communication","problem_solving"))],
  },
  {
    "filename": "travel-and-tourism-6016.json",
    "subjectCode": "6016", "subjectName": "Travel and Tourism", "syllabusYear": 2024,
    "construct": "Applies travel and tourism knowledge to manage destinations, operations and sustainable visitor experiences.",
    "elementsOfConstruct": [
      eoc("EoC1","Explores tourism dynamics, understand, travellers’ destinations and global challenges in",
          "Explores tourism dynamics, destinations and global challenges",
          ["Tourism dynamics","Destinations","Global tourism"],["Sustainable tourism"]),
      eoc("EoC2","Manages tourism destinations and operations",
          "Manages tourism destinations and operations",
          ["Destination management","Tourism operations"],["Attractions"]),
      eoc("EoC3","Applies key principles of the hospitality industry in travel and tourism",
          "Applies hospitality principles within travel and tourism",
          ["Hospitality in tourism","Customer care"],["Accommodation"]),
      eoc("EoC4","Operates tourism events and activities",
          "Operates tourism events and activities",
          ["Events","Tourism activities"],["Festivals"]),
      eoc("EoC5","Conducts tour operations",
          "Conducts tour operations",
          ["Tour operations","Tour guiding"],["Itinerary planning"]),
    ],
    "testDesign": td("6016", 5, 5, 100, 5, 100,
      "SBA Form 2-3; Final Exam Form 4. Codes 6016/1 and 6016/2.",
      sba_bloom=("understanding","creating"), fe_bloom=("understanding","evaluating")),
    "scoringCriteria": rules("SBA school-marked.","Final Exam ECZ-marked.","Both components required."),
    "exemplars": [ex("EoC5","Tour operations itinerary for a Zambian destination with visitor challenges",
      [{"label":"(a)","marks":8,"bloomLevel":"applying"},{"label":"(b)","marks":12,"bloomLevel":"evaluating"}],
      ("problem_solving","communication"))],
  },
  {
    "filename": "physical-education-9010.json",
    "subjectCode": "9010", "subjectName": "Physical Education and Sport", "syllabusYear": 2024,
    "construct": "Applies Perceptual motor movement, problem solving, Interpersonal and intrapersonal skills to enhance Physical Fitness, mental wellbeing and lifelong health habits in creativity and Entrepreneurship.",
    "elementsOfConstruct": [
      eoc("EoC1","Understands health related activities in physical education",
          "Assesses health-related activities and sports nutrition",
          ["Health-related fitness","Sports nutrition","Physical fitness"],["Wellness"]),
      eoc("EoC2","Demonstrates motor activities in sports",
          "Assesses movements, perceptual learning and fitness activities",
          ["Motor skills","Perceptual learning","Fitness activities"],["Sports skills"]),
      eoc("EoC3","Understands human body and its movements",
          "Understands body systems, forces and biomechanics in sports",
          ["Human body","Biomechanics","Body systems"],["Forces in sport"]),
      eoc("EoC4","Applies entreprenuerial skills",
          "Entrepreneurship and legal/ethical issues in sports",
          ["Sports entrepreneurship","Ethics in sport"],["Sports law"]),
      eoc("EoC5","Applies athletics skills management of sports events and facilities",
          "Sports management, organisation and skills development",
          ["Athletics","Sports management","Facilities"],["Event organisation"]),
    ],
    "testDesign": td("9010", 7, 7, 100, 5, 100,
      "SBA Form 2-3 (7 tasks each/100). Final Exam 5 items/100, 2h30. Weighting SBA:FE 40:60.",
      sba_bloom=("remembering","creating"), fe_bloom=("understanding","evaluating")),
    "scoringCriteria": rules("SBA 40%, Final Exam 60%.","Both components required."),
    "exemplars": [ex("EoC1","Health-related PE and sports nutrition scenario for school athletes",
      [{"label":"(a)","marks":8,"bloomLevel":"understanding"},{"label":"(b)","marks":12,"bloomLevel":"applying"}],
      ("problem_solving","critical_thinking"))],
  },
  {
    "filename": "computer-science-8010.json",
    "subjectCode": "8010", "subjectName": "Computer Science", "syllabusYear": 2024,
    "construct": "Demonstrates proficiency in designing, developing, and applying computational solutions to real-world problems, guided by Computer Science principles and prioritising ethics and responsible digital citizenship.",
    "elementsOfConstruct": [
      eoc("EoC1","Recognises computer system components to build and troubleshoot computer systems everyday life",
          "Identifies components, understands functions, assembles and troubleshoots systems",
          ["Computer components","Hardware","Troubleshooting","System assembly"],["Input output devices"]),
      eoc("EoC2","Analyses, computer tools based on their roles in problem solving",
          "Analyses, classifies and distinguishes computer tools by problem-solving role",
          ["Software tools","Applications","Problem solving tools"],["Utilities"]),
      eoc("EoC3","Analyses computing concepts by identifying relationships, principles and underlying structures",
          "Investigates core computing concepts and how they interconnect in digital systems",
          ["Computing concepts","Algorithms","Data structures"],["Networks basics"]),
      eoc("EoC4","Applies computational knowledge to critically evaluate situations and make informed technological decisions",
          "Computational thinking to evaluate options on efficiency, ethics, safety and impact",
          ["Computational thinking","Ethics","Decision making"],["Digital citizenship"]),
      eoc("EoC5","Creates and designs systems that solve real life problems and improve way of life for citizens",
          "Designs/develops creative functional user-centred digital solutions for societal needs",
          ["Programming","System design","Software development"],["Project work"]),
    ],
    "testDesign": td("8010", 9, 7, 100, 5, 100,
      "SBA Form 2: 9 tasks; Form 3: 7 tasks (incl. project). Final Exam 5 items/100, 2h30. Weighting 30:70.",
      sba_bloom=("understanding","creating"), fe_bloom=("remembering","creating")),
    "scoringCriteria": rules("SBA: exercises, practicals, assignments, project.","Final Exam ECZ-marked.","Both components required."),
    "exemplars": [ex("EoC5","Design a digital solution for a Zambian community problem (user-centred)",
      [{"label":"(a)","marks":8,"bloomLevel":"analysing"},{"label":"(b)","marks":12,"bloomLevel":"creating"}],
      ("creativity_and_innovation","problem_solving","digital_literacy"))],
  },
  {
    "filename": "ict-8011.json",
    "subjectCode": "8011", "subjectName": "Information and Communications Technology", "syllabusYear": 2024,
    "construct": "Applies digital literacy and computational understanding to interpret problems, create solution-driven approaches, and use Information and Communications Technology (ICT) responsibly and effectively in real-life applications.",
    "elementsOfConstruct": [
      eoc("EoC1","Demonstrate the ability to identify and describe ICT components, systems and their functions",
          "Recognises components and explains input/processing/storage/output working together",
          ["ICT components","Computer systems","Input output storage"],["Hardware"]),
      eoc("EoC2","Classify and distinguish ICT tools, file types, network structures, and technologies",
          "Categorises tools, differentiates file formats, compares network topologies/technologies",
          ["ICT tools","File types","Networks","Topologies"],["Software types"]),
      eoc("EoC3","Develops analytical skills and evaluating ICT systems and problems",
          "Assesses system behaviour, resolves operational issues, recommends improvements",
          ["System analysis","Troubleshooting","Configuration"],["Operational issues"]),
      eoc("EoC4","Evaluate ICT systems, networks and technologies",
          "Examines performance, compares alternatives, considers sustainability/security/user impact",
          ["System evaluation","Network evaluation","Security"],["Sustainability"]),
      eoc("EoC5","Applies ethical reasoning in the responsible use of ICT",
          "Digital rights, privacy, security; responsible and safe technology use",
          ["ICT ethics","Privacy","Digital rights","Cyber safety"],["Responsible use"]),
    ],
    "testDesign": td("8011", 9, 7, 100, 5, 100,
      "SBA Form 2: 9 tasks; Form 3: 7 tasks. Final Exam 5 items/100, 2h30.",
      sba_bloom=("understanding","creating"), fe_bloom=("understanding","evaluating")),
    "scoringCriteria": rules("SBA school-marked.","Final Exam ECZ-marked.","Both components required."),
    "exemplars": [ex("EoC5","School ICT policy scenario on privacy, cyber safety and responsible use",
      [{"label":"(a)","marks":8,"bloomLevel":"understanding"},{"label":"(b)","marks":12,"bloomLevel":"evaluating"}],
      ("digital_literacy","critical_thinking"))],
  },
  {
    "filename": "commerce-7015.json",
    "subjectCode": "7015", "subjectName": "Commerce", "syllabusYear": 2024,
    "construct": "Demonstrates strong commercial competences, entrepreneurial skills and ethical values for personal empowerment and effective participation in economic activities and national development.",
    "elementsOfConstruct": [
      eoc("EoC1","Demonstrates the skills of clean production and trading within legal parameters",
          "Commerce concepts, production/services/specialisation, factors of production, sustainable trade, credit, contracts/trade law, domestic/international business documentation",
          ["Commerce","Production","Factors of production","Trade","Contracts","Domestic trade","International trade"],
          ["Credit","Specialisation","Trade restrictions"]),
      eoc("EoC2","Demonstrates skills in entrepreneurship, Business formation and financing",
          "Entrepreneurial skills, financing/capital/liquidity, business formation and operational analysis",
          ["Entrepreneurship","Business formation","Business finance","Capital"],["Liquidity","Business ideas"]),
      eoc("EoC3","Applies physical and Online Business practices free from exploitation",
          "E-commerce, consumer protection, data privacy, online payment systems",
          ["E-Commerce","Online business","Consumer protection","Online payments"],["Cyber exploitation","Data privacy"]),
      eoc("EoC4","Analyses and evaluates the significance of commercial services in production, commerce and direct service provision",
          "Evaluates commercial services' role in production, commerce and direct services",
          ["Commercial services","Insurance","Banking","Transport","Warehousing"],["Advertising"]),
    ],
    "testDesign": td("7015", 6, 6, 100, 5, 100,
      "SBA Form 2-3 scenario/tasks. Final Exam Form 4. Codes 7015/1 and 7015/2. Weighting typically 30:70.",
      sba_bloom=("understanding","creating"), fe_bloom=("understanding","evaluating")),
    "scoringCriteria": rules("SBA school-marked.","Final Exam ECZ-marked.","Both components required."),
    "exemplars": [ex("EoC2","Zambian SME formation and financing scenario (capital/liquidity challenges)",
      [{"label":"(a)","marks":8,"bloomLevel":"applying"},{"label":"(b)","marks":12,"bloomLevel":"evaluating"}],
      ("financial_literacy","problem_solving","analytical_thinking"))],
  },
  {
    "filename": "principles-of-accounts-7020.json",
    "subjectCode": "7020", "subjectName": "Principles of Accounts", "syllabusYear": 2024,
    "construct": "Applies accounting principles to record, verify and report financial information for sound business decisions.",
    "elementsOfConstruct": [
      eoc("EoC1","Demonstrates sound accounting decisions based on key accounting principles or concepts,",
          "Applies key accounting principles/concepts for sound decisions",
          ["Accounting principles","Accounting concepts","Accounting equation"],["Double entry basics"]),
      eoc("EoC2","Demonstrates proficiency in recording business transactions in ledger accounts",
          "Records business transactions in ledger accounts",
          ["Ledger accounts","Journal entries","Books of original entry"],["Cash book"]),
      eoc("EoC3","Analyses the effective implementation of reconciliation and verification tools in accounting",
          "Implements reconciliation and verification tools effectively",
          ["Bank reconciliation","Control accounts","Trial balance","Verification"],["Errors"]),
      eoc("EoC4","Prepares and analyses financial statements",
          "Prepares and analyses financial statements",
          ["Financial statements","Income statement","Statement of financial position","Ratio analysis"],
          ["Gross profit margin","Net profit margin"]),
    ],
    "testDesign": td("7020", 6, 6, 100, 5, 100,
      "SBA Form 2-3: 6 tasks each (Form 3 includes subject project Terms 2-3). Final Exam Form 4, 100 marks. Codes 7020/1 and 7020/2.",
      sba_bloom=("understanding","creating"), fe_bloom=("understanding","evaluating"), min_parts=2),
    "scoringCriteria": rules(
      "SBA school-marked formative/summative tasks; evidence retained.",
      "Final Exam ECZ-marked.",
      "Candidates without SBA are not graded (no partial processing).",
      "Both components contribute to final score."),
    "exemplars": [ex("EoC4","Prepare and analyse financial statements for a Zambian trading business (ratios/margins)",
      [{"label":"(a)","marks":10,"bloomLevel":"applying"},{"label":"(b)","marks":10,"bloomLevel":"analysing"}],
      ("financial_literacy","analytical_thinking","problem_solving"))],
  },
]

def main():
  OUT.mkdir(parents=True, exist_ok=True)
  for raw in SPECS:
    spec = dict(raw)
    filename = spec.pop("filename")
    # strip accidental keys
    spec.pop("note_field", None)
    path = OUT / filename
    path.write_text(json.dumps(spec, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print("wrote", path.name)

if __name__ == "__main__":
  main()
