export const STUDENT_DB_MAPPING_ROWS = [
  {
    column: 'Full Name *',
    required: true,
    table: 'User',
    field: 'name',
    notes: 'Also copied to Student.name',
  },
  {
    column: 'Date of Birth * (YYYY-MM-DD)',
    required: true,
    table: 'User',
    field: 'date_of_birth',
    notes: 'Student must be at least 12 years old',
  },
  {
    column: 'Gender *',
    required: true,
    table: 'User',
    field: 'gender',
    notes: 'Male or Female (stored as male/female)',
  },
  {
    column: 'Email *',
    required: true,
    table: 'User',
    field: 'email',
    notes: 'Unique per school (User @@unique [schoolId, email])',
  },
  {
    column: 'Password * (min 8 chars)',
    required: true,
    table: 'User',
    field: 'password',
    notes: 'Hashed with bcrypt before save',
  },
  {
    column: 'Exam Number *',
    required: true,
    table: 'Student',
    field: 'exam_number',
    notes: 'Unique per school',
  },
  {
    column: 'Year Group / Grade *',
    required: true,
    table: 'Class',
    field: 'year_group, name',
    notes: 'Combined with Section to form Class.name (e.g. Form 1A)',
  },
  {
    column: 'Section (A–Z)',
    required: false,
    table: 'Class',
    field: 'section',
    notes: 'Defaults to A when blank',
  },
  {
    column: 'Subjects * (comma separated)',
    required: true,
    table: 'PupilSubjectEnrollment',
    field: 'subjectId, classId, pupilId',
    notes: 'Matched by Subject.name in your school catalog',
  },
  {
    column: "Father's Full Name",
    required: false,
    table: 'Student',
    field: 'parent_father_name',
    notes: '',
  },
  {
    column: "Father's Contact",
    required: false,
    table: 'Student',
    field: 'parent_father_contact',
    notes: 'Zambian phone format (+260… or 0…)',
  },
  {
    column: '(auto)',
    required: true,
    table: 'User',
    field: 'role',
    notes: 'Always set to student',
  },
  {
    column: '(auto)',
    required: true,
    table: 'Student',
    field: 'userId, classId, schoolId',
    notes: 'Linked on import',
  },
]
