export const TEACHER_DB_MAPPING_ROWS = [
  {
    column: 'Full Name *',
    required: true,
    table: 'User',
    field: 'name',
    notes: 'Display name for login and profile',
  },
  {
    column: 'Email *',
    required: true,
    table: 'User',
    field: 'email',
    notes: 'Unique per school (User @@unique [schoolId, email])',
  },
  {
    column: 'Password * (min 8 chars)',
    required: true,
    table: 'User',
    field: 'password',
    notes: 'Hashed with bcrypt before save',
  },
  {
    column: 'Contact Number',
    required: false,
    table: 'User',
    field: 'contact_number',
    notes: 'Zambian phone (+260… or 0…)',
  },
  {
    column: 'Gender',
    required: false,
    table: 'User',
    field: 'gender',
    notes: 'Male or Female',
  },
  {
    column: 'Date of Birth (YYYY-MM-DD)',
    required: false,
    table: 'User',
    field: 'date_of_birth',
    notes: '',
  },
  {
    column: 'Employee ID',
    required: false,
    table: 'User',
    field: 'employeeId',
    notes: 'Staff reference number',
  },
  {
    column: 'Department(s) *',
    required: true,
    table: 'Department, TeacherDepartment',
    field: 'name, departmentId',
    notes: 'Comma-separated; matched or created per school',
  },
  {
    column: 'TS Number *',
    required: true,
    table: 'Teacher',
    field: 'ts_number',
    notes: 'Teaching Service number',
  },
  {
    column: 'Qualifications',
    required: false,
    table: 'Teacher',
    field: 'qualifications',
    notes: '',
  },
  {
    column: 'Specialization',
    required: false,
    table: 'Teacher',
    field: 'specialization',
    notes: '',
  },
  {
    column: 'Assigned Subjects (comma separated)',
    required: false,
    table: 'Teacher',
    field: 'assignedSubjects',
    notes: 'Subject names stored on teacher profile',
  },
  {
    column: 'Teaching Assignments (Class:Subject; …)',
    required: false,
    table: 'TeachingAssignment',
    field: 'classId, subjectId, teacherId',
    notes: 'e.g. Form 1A:Mathematics; Form 2B:English — classes/subjects matched by name',
  },
  {
    column: '(auto)',
    required: true,
    table: 'User',
    field: 'role',
    notes: 'Always set to teacher',
  },
  {
    column: '(auto)',
    required: true,
    table: 'Teacher',
    field: 'userId, schoolId, department',
    notes: 'Primary department string + profile row',
  },
]
