/**
 * Models that have a schoolId column and must never be queried without tenant scope
 * when using getTenantClient / ALS enforcement.
 *
 * Keep PLATFORM_MODELS (no schoolId / cross-tenant) in tenantClient.js.
 * Regenerate candidates via: node -e "..." or scripts/check-tenant-scoping.ts --list-models
 */
export const TENANT_SCOPED_MODELS = new Set([
  'User',
  'Student',
  'Teacher',
  'HeadOfDepartment',
  'Class',
  'Subject',
  'Department',
  'Result',
  'Attendance',
  'AttendanceMark',
  'AttendanceSession',
  'EczAssessment',
  'EczAssessmentScore',
  'TermReport',
  'SchoolFeePayment',
  'ParentProfile',
  'ParentStudentLink',
  'SmsContactOptOut',
  'ConsentRecord',
  'SchoolMaterial',
  'MaterialChunk',
  'TimetableEntry',
  'TimetableAllocationEntry',
  'TimetableVersion',
  'TimeSlot',
  'SmsBroadcast',
  'SmsQueueItem',
  'SmsLog',
  'AuditLog',
  'TeachingAssignment',
  'Goal',
  'StudyMaterial',
  'MockExamAttempt',
  'FlashcardDeck',
  'LessonPlan',
  'TeacherPeriodAssignment',
  'Classroom',
  'Notification',
  'SBASubjectPolicy',
  'SBAComponentPolicy',
  'SBARecord',
  'SBARecordEdit',
])
